<a href="https://colab.research.google.com/github/almasfiza/Data-Science/blob/master/WeekOneB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Coursera - Introduction to Data Science**
**Week One Part 2: Introduction to NumPy**

In [1]:
#importing the NumPy package
import numpy as np

In [3]:
#working with arrays in NumPy- creare a list and convert to numpy array
li = [ 1, 2 ,3]
arr = np.array(li)
arr

array([1, 2, 3])

In [5]:
#multidimensional array using nested lists
book = np.array([["The Count of Monte Cristo","Anna Karenina"],["Alexander Dumas","Leo Tolstoy"]])
book

array([['The Count of Monte Cristo', 'Anna Karenina'],
       ['Alexander Dumas', 'Leo Tolstoy']], dtype='<U25')

In [6]:
#shape method is used to find the dimensions of the array
book.shape

(2, 2)

In [7]:
arr.shape


(3,)

In [11]:
# arange method returns evenly spaced values in an interval
n = np.arange(0,30,10) # begin at 0, end at 30 and have a jump of 10 values
n

array([ 0, 10, 20])

In [17]:
# reshape is used to change the shape of the array but keeping the data same
data = np.arange(0,30,2)
print(data.shape)
data

(15,)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [18]:
#reshape
data.reshape(3,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [21]:
#linspace returns evenly spaced numbers over an interval
o = np.linspace(1,9,9)
o

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
#reshape the o
o.reshape(3,3)
#make sure to store the o.shape in another array since it is immutable
matrix = o.reshape(3,3)

In [27]:
#ones gives a new array with all the elements as ones
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
#similarly zeros gives a new array with all the elements as zeroes
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
#eye gives a unit matrix- ones on the diagnols and zeros everywhere else
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
#to extract the diagnol
np.diag(matrix)

array([1., 5., 9.])

In [34]:
#creating an array using a repeating list or np.tile
np.array([1,2] * 3)

array([1, 2, 1, 2, 1, 2])

In [36]:
np.tile([1,2],2)

array([1, 2, 1, 2])

In [37]:
#repeat elements of the array using repeat
#note for a list a,b the tile function gives ababababab.... while the repeat
#function gives aaaaaaabbbbbb
np.repeat([1,2,3],2)


array([1, 1, 2, 2, 3, 3])

**COMBINING ARRAYS**

In [38]:
p = np.ones([2,3],int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [41]:
#vstack is used to stack arrays in a sequence vertically- rowwise, similar to
#the repeat function
np.vstack([p,2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [42]:
#hstack is used to stack the arrays in column wise, horizontally
np.hstack([p,2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

**OPERATIONS**

In [45]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
#simple operations
print(x)
print(y)
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x**2)

[1 2 3]
[4 5 6]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [46]:
#dot product
x.dot(y)

32

In [48]:
print(len(x))#rows of x

3


In [51]:
mat = np.array([[1,2,3],[4,5,6]])

In [53]:
#shape before transposing
mat.shape

(2, 3)

In [54]:
#transposing
mat.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [55]:
mat.T.shape

(3, 2)

In [57]:
mat.dtype
#figuring out the data type of the elements in the array

dtype('int64')

In [59]:
#type casting
mat = mat.astype('f')
mat.dtype

dtype('float32')

**MATH FUNCTIONS**

In [60]:
a = np.array([-2,-1,0,1,2])

In [61]:
a.sum()

0

In [62]:
a.max()

2

In [63]:
a.min()

-2

In [64]:
a.mean()

0.0

In [65]:
a.std()

1.4142135623730951

In [67]:
#argmax and argmin return the index of the max and min elements respectively
print(a.argmax())
print(a.argmin())

4
0


**INDEXING AND SLICING**

In [68]:
s = np.arange(13)**2

In [69]:
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [70]:
s[0],s[10]

(0, 100)

In [71]:
s[-1],s[-3]

(144, 100)

In [72]:
s[1:5]

array([ 1,  4,  9, 16])

In [73]:
s[:5]

array([ 0,  1,  4,  9, 16])

In [74]:
s[5:]

array([ 25,  36,  49,  64,  81, 100, 121, 144])

In [76]:
# A second : can be used to indicate step-size. array[start:stop:stepsize]
s[::2]

array([  0,   4,  16,  36,  64, 100, 144])

In [77]:
#working on multi-dimensional array
matrix = np.arange(36)
matrix.resize((6,6)) # note that resize affects the same array while reshape makes a new array
matrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [78]:
matrix[2,2]

14

In [79]:
np.diag(matrix)

array([ 0,  7, 14, 21, 28, 35])

In [80]:
#taking the last three elements of the third row.
matrix[2,-3:]

array([15, 16, 17])

In [81]:
#selecting all the rows up to row 2 (not inclusive) and all the columns up
#to and not including the last column
matrix[:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [84]:
#selecting values from the array greater than 70
matrix[matrix > 32]

array([33, 34, 35])

In [85]:
#changing the values greater than 32 to 32
matrix[matrix>32]=32
matrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 32, 32, 32]])

**COPYING DATA**


In [86]:
matrix

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 32, 32, 32]])

In [87]:
matrix1 = matrix[:3,:3]
matrix1

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [88]:
# : is used to select the whole array
matrix1[:] = 0
matrix1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [89]:
matrix

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 32, 32, 32]])

even matrix has been changed


In [92]:
#to avoid the reflections of matrix1 in matrix, use the matrix.copy
matrix_copy= matrix.copy()
matrix_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 32, 32, 32]])

In [94]:
matrix_copy[:]=2
matrix_copy

array([[2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2]])

In [95]:
matrix

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 32, 32, 32]])

**ITERATING OVER ARRAYS**

In [96]:
#let's create a new array test of some order
test = np.random.randint(0,10,(4,3))
test

array([[1, 4, 0],
       [1, 6, 5],
       [7, 2, 6],
       [6, 5, 8]])

In [97]:
#iterate by row
for row in test:
  print(row)

[1 4 0]
[1 6 5]
[7 2 6]
[6 5 8]


In [98]:
#iterate by index
for i in range(len(test)):
  print(test[i])

[1 4 0]
[1 6 5]
[7 2 6]
[6 5 8]


In [99]:
#iterating by row and index
for i, row in enumerate(test):
  print('row', i, 'is', row)

row 0 is [1 4 0]
row 1 is [1 6 5]
row 2 is [7 2 6]
row 3 is [6 5 8]


In [100]:
# use zip to iterate over multiple iterables
test2 =  test**2
test2

array([[ 1, 16,  0],
       [ 1, 36, 25],
       [49,  4, 36],
       [36, 25, 64]])

In [101]:
for i, j in zip(test, test2):
  print(i, '   ', j)

[1 4 0]     [ 1 16  0]
[1 6 5]     [ 1 36 25]
[7 2 6]     [49  4 36]
[6 5 8]     [36 25 64]
